export const wordHints: Record<string, string> = {
  'Cepelinas': 'bulvės',
  'Gitanas Nausėda': 'prezidentas',
  'Maybachas': 'prabanga',
  'Auksinis kardas': 'ginklas',
  'Krabas': 'jūra',
  'Šaltibarščiai': 'sriuba',
  'Pink Soup': 'rūžava',
  'Luktelk': 'laida',
  'The Roop': 'grupė',
  'Marozas': 'šaltis',
  'Forsas': 'serialas',
  'Perekūpas': 'prekyba',
  'Žalgiris': 'krepšinis',
  'Krepšinis': 'sportas',
  'Kugelis': 'bulvės',
  'Vėdarai': 'žarnos',
  'Gariūnai': 'turgus',
  'Akropolis': 'parduotuvė',
  'Boltukas': 'automobilis',
  'Woltas': 'pristatymas',
  'Maxima': 'parduotuvė',
  'Lidlas': 'parduotuvė',
  'Eurovizija': 'konkursas',
  'Vilnius': 'sostinė',
  'Kaunas': 'miestas',
  'Palanga': 'pajūris',
  'Šventoji': 'pajūris',
  'Nida': 'nerija',
  'Trakai': 'pilis',
  'Kryžių kalnas': 'kryžiai',
  'Gedimino pilis': 'pilis',
  'Užupis': 'rajonas',
  'Konstitucija': 'įstatymas',
  'Mercedes 124': 'automobilis',
  'Kregždė': 'paukštis',
  'Ryklis': 'plėšrūnas',
  'Bulka': 'duona',
  'Silkė': 'žuvis',
  'Passatas': 'automobilis',
  'Varškės sūrelis': 'pienas',
  'Magija': 'triukas',
  'Džiugas': 'sūris',
  'Šakotis': 'tortas',
  'Grybukai': 'užkandis',
  'Kebabas': 'mėsa',
  'Bambalis': 'žargonas',
  'Alutis': 'gėrimas',
  'Samagonas': 'naminė',
  'Konservai': 'skardinė',
  'Valstiečiai': 'partija',
  'Laisvės partija': 'partija',
  'Andrius Tapinas': 'žurnalistas',
  'Skirmantas Malinauskas': 'politikas',
  'Minedas': 'blogeris',
  'Antanas Juknevičius': 'dainininkas',
  'Dakaras': 'ralis',
  'Žydrūnas Savickas': 'stipruolis',
  'Arvydas Sabonis': 'krepšinis',
  'Jonas Valančiūnas': 'krepšinis',
  'Pijokas': 'alkoholis',
  'Švyturys': 'alus',
  'Kalnapilis': 'alus',
  'OG Version': 'originalas',
  'Lietuva': 'šalis',
  'Gintaras': 'akmuo',
  'Linas': 'augalas',
  'Duona': 'kepinys',
  'Pienas': 'baltas',
  'Medus': 'saldus',
  'Vytis': 'herbas',
  'Gediminas': 'kunigaikštis',
  'Vytautas': 'kunigaikštis',
  'Mindaugas': 'karalius',
  'Dalia Grybauskaitė': 'prezidentė',
  'Valdas Adamkus': 'prezidentas',
  'Rūta Meilutytė': 'plaukimas',
  'Donatas Montvydas': 'dainininkas',
  'Marijonas Mikutavičius': 'dainininkas',
  'Andrius Mamontovas': 'rokas',
  'Jazzu': 'dainininkas',
  'Beata Nicholson': 'dainininkas',
  'Martynas Levickis': 'akordeonas',
  'Monika Liu': 'eurovizija',
  'Gabrielius Landsbergis': 'politikas',
  'Ingrida Šimonytė': 'politikė',
  'Ramūnas Karbauskis': 'politikas',
  'Viktoras Uspaskich': 'politikas',
  'Rolandas Paksas': 'prezidentas',
  'Vytautas Šapranauskas': 'humoristas',
  'Algis Greitai': 'komedija',
  'Mantas Katleris': 'internetas',
  'Justinas Jankevičius': 'dainininkas',
  'Indrė Stonkuvienė': 'atlikėja',
  'Naglis Bierancas': 'žurnalistas',
  'Sūrūs agurkėliai': 'rūgštus',
  'Silkė pataluose': 'žuvis',
  'Grybai': 'miškas',
  'Miškas': 'medžiai',
  'Kiesa': 'pinigai',
  'Giedrė Beleauskaitė': 'atlikėja',
  'Karolina Meschino': 'atlikėja',
  'Agnė Jagelavičiūtė': 'atlikėja',
  'Orijus Gasanovas': 'dainininkas',
  'Paulius de Miko': 'dainininkas',
  'Daina Bosas': 'dainininkas',
  'Natalija Bunkė': 'atlikėja',
  'Mia': 'atlikėja',
  'Vidas Bareikis': 'aktorius',
  'Egidijus Dragūnas': 'muzikantas',
  'Selas': 'dainininkas',
  'Rytis Cicinas': 'vedėjas',
  'Radžis': 'dainininkas',
  'Žilvinas Žvagulis': 'politikas',
  'Irena Starošaitė': 'atlikėja',
  'Vudis': 'humoristas',
  'Mino': 'dainininkas',
  'Radistai': 'grupė',
  'Jonas Nainys': 'sportininkas',
  'Rolandas Mackevičius': 'vedėjas',
  'Whydotas': 'internetas',
  'Flying Saucer Gang': 'grupė',
  'BA.': 'repas',
  'G&G Sindikatas': 'grupė',
  'Jovani': 'daina',
  'Dynoro': 'muzikantas',
  'Jautiena': 'mėsa',
  'Kiauliena': 'mėsa',
  'Vištiena': 'paukštiena',
  'Kumpis': 'rūkyta',
  'Dešrelės': 'dešra',
  'Kotletas': 'malta',
  'Blynai': 'kepinys',
  'Šaukštas': 'įrankis',
  'Šakutė': 'įrankis',
  'Peilis': 'aštrus',
  'Kibiras': 'talpykla',
  'Šluota': 'valymas',
  'Šampūnas': 'plaukai',
  'Rankšluostis': 'vonios',
  'BMW': 'automobilis',
  'Audi': 'automobilis',
  'Volkswagen': 'automobilis',
  'Toyota': 'japonija',
  'Renault': 'prancūzija',
  'Dviratis': 'ratai',
  'Paspirtukas': 'transportas',
  'Kojinės': 'kojos',
  'Kelnes': 'drabužis',
  'Striukė': 'šiltas',
  'Batus': 'avalynė',
  'Kepurė': 'galva',
  'Piniginė': 'pinigai',
  'Diržas': 'kelnes',
  'Telefonas': 'ryšys',
  'Kompiuteris': 'elektronika',
  'Ausinės': 'muzika',
  'Kroviklis': 'baterija',
  'Atsuktuvas': 'varžtas',
  'Šaldytuvas': 'šaltas',
  'Virdulys': 'karštas',
}

export type WordCategoryKey = 'lithuanian'

export type WordCategory = {
  label: string
  words: string[]
}

export const wordCategories: Record<WordCategoryKey, WordCategory> = {
  lithuanian: {
    label: 'Lietuviška DB',
    words: [
      'Cepelinas',
      'Gitanas Nausėda',
      'Maybachas',
      'Auksinis kardas',
      'Krabas',
      'Šaltibarščiai',
      'Pink Soup',
      'Luktelk',
      'The Roop',
      'Marozas',
      'Forsas',
      'Perekūpas',
      'Žalgiris',
      'Krepšinis',
      'Kugelis',
      'Vėdarai',
      'Gariūnai',
      'Akropolis',
      'Boltukas',
      'Woltas',
      'Maxima',
      'Lidlas',
      'Eurovizija',
      'Vilnius',
      'Kaunas',
      'Palanga',
      'Šventoji',
      'Nida',
      'Trakai',
      'Kryžių kalnas',
      'Gedimino pilis',
      'Užupis',
      'Konstitucija',
      'Mercedes 124',
      'Kregždė',
      'Ryklis',
      'Bulka',
      'Silkė',
      'Passatas',
      'Varškės sūrelis',
      'Magija',
      'Džiugas',
      'Šakotis',
      'Grybukai',
      'Kebabas',
      'Bambalis',
      'Alutis',
      'Samagonas',
      'Konservai',
      'Valstiečiai',
      'Laisvės partija',
      'Andrius Tapinas',
      'Skirmantas Malinauskas',
      'Minedas',
      'Antanas Juknevičius',
      'Dakaras',
      'Žydrūnas Savickas',
      'Arvydas Sabonis',
      'Jonas Valančiūnas',
      'Pijokas',
      'Švyturys',
      'Kalnapilis',
      'OG Version',
      'Lietuva',
      'Gintaras',
      'Linas',
      'Duona',
      'Pienas',
      'Medus',
      'Vytis',
      'Gediminas',
      'Vytautas',
      'Mindaugas',
      'Dalia Grybauskaitė',
      'Valdas Adamkus',
      'Rūta Meilutytė',
      'Donatas Montvydas',
      'Marijonas Mikutavičius',
      'Andrius Mamontovas',
      'Jazzu',
      'Beata Nicholson',
      'Martynas Levickis',
      'Monika Liu',
      'Gabrielius Landsbergis',
      'Ingrida Šimonytė',
      'Ramūnas Karbauskis',
      'Viktoras Uspaskich',
      'Rolandas Paksas',
      'Vytautas Šapranauskas',
      'Algis Greitai',
      'Mantas Katleris',
      'Justinas Jankevičius',
      'Indrė Stonkuvienė',
      'Naglis Bierancas',
      'Sūrūs agurkėliai',
      'Silkė pataluose',
      'Grybai',
      'Miškas',
      'Kiesa',
      'Giedrė Beleauskaitė',
      'Karolina Meschino',
      'Agnė Jagelavičiūtė',
      'Orijus Gasanovas',
      'Paulius de Miko',
      'Daina Bosas',
      'Natalija Bunkė',
      'Mia',
      'Vidas Bareikis',
      'Egidijus Dragūnas',
      'Selas',
      'Rytis Cicinas',
      'Radžis',
      'Žilvinas Žvagulis',
      'Irena Starošaitė',
      'Vudis',
      'Mino',
      'Radistai',
      'Jonas Nainys',
      'Rolandas Mackevičius',
      'Whydotas',
      'Flying Saucer Gang',
      'BA.',
      'G&G Sindikatas',
      'Jovani',
      'Dynoro',
      'Jautiena',
      'Kiauliena',
      'Vištiena',
      'Kumpis',
      'Dešrelės',
      'Kotletas',
      'Blynai',
      'Šaukštas',
      'Šakutė',
      'Peilis',
      'Kibiras',
      'Šluota',
      'Šampūnas',
      'Rankšluostis',
      'BMW',
      'Audi',
      'Volkswagen',
      'Toyota',
      'Renault',
      'Dviratis',
      'Paspirtukas',
      'Kojinės',
      'Kelnes',
      'Striukė',
      'Batus',
      'Kepurė',
      'Piniginė',
      'Diržas',
      'Telefonas',
      'Kompiuteris',
      'Ausinės',
      'Kroviklis',
      'Atsuktuvas',
      'Šaldytuvas',
      'Virdulys',
    ],
  },
}
