export type WordCategoryKey = 'lithuanian'

export type WordCategory = {
  label: string
  words: string[]
}

export const wordCategories: Record<WordCategoryKey, WordCategory> = {
  lithuanian: {
    label: 'Lietuviška DB',
    words: [
      'Cepelinas',
      'Gitanas Nausėda',
      'Maybachas',
      'Auksinis kardas',
      'Krabas',
      'Šaltibarščiai',
      'Pink Soup',
      'Luktelk',
      'The Roop',
      'Marozas',
      'Forsas',
      'Perekūpas',
      'Žalgiris',
      'Krepšinis',
      'Kugelis',
      'Vėdarai',
      'Gariūnai',
      'Akropolis',
      'Boltukas',
      'Woltas',
      'Maxima',
      'Lidlas',
      'Eurovizija',
      'Vilnius',
      'Kaunas',
      'Palanga',
      'Šventoji',
      'Nida',
      'Trakai',
      'Kryžių kalnas',
      'Gedimino pilis',
      'Užupis',
      'Konstitucija',
      'Mercedes 124',
      'Kregždė',
      'Ryklis',
      'Bulka',
      'Silkė',
      'Passatas',
      'Varškės sūrelis',
      'Magija',
      'Džiugas',
      'Šakotis',
      'Grybukai',
      'Kebabas',
      'Bambalis',
      'Alutis',
      'Samagonas',
      'Konservai',
      'Valstiečiai',
      'Laisvės partija',
      'Andrius Tapinas',
      'Skirmantas Malinauskas',
      'Minedas',
      'Antanas Juknevičius',
      'Dakaras',
      'Žydrūnas Savickas',
      'Arvydas Sabonis',
      'Jonas Valančiūnas',
      'Pijokas',
      'Švyturys',
      'Kalnapilis',
      'OG Version',
      'Lietuva',
      'Gintaras',
      'Linas',
      'Duona',
      'Pienas',
      'Medus',
      'Vytis',
      'Gediminas',
      'Vytautas',
      'Mindaugas',
      'Dalia Grybauskaitė',
      'Valdas Adamkus',
      'Rūta Meilutytė',
      'Donatas Montvydas',
      'Marijonas Mikutavičius',
      'Andrius Mamontovas',
      'Jazzu',
      'Beata Nicholson',
      'Martynas Levickis',
      'Monika Liu',
      'Gabrielius Landsbergis',
      'Ingrida Šimonytė',
      'Ramūnas Karbauskis',
      'Viktoras Uspaskich',
      'Rolandas Paksas',
      'Vytautas Šapranauskas',
      'Algis Greitai',
      'Mantas Katleris',
      'Justinas Jankevičius',
      'Indrė Stonkuvienė',
      'Naglis Bierancas',
      'Sūrūs agurkėliai',
      'Silkė pataluose',
      'Grybai',
      'Miškas',
      'Kiesa',
      'Giedrė Beleauskaitė',
      'Karolina Meschino',
      'Agnė Jagelavičiūtė',
      'Orijus Gasanovas',
      'Paulius de Miko',
      'Daina Bosas',
      'Natalija Bunkė',
      'Mia',
      'Vidas Bareikis',
      'Egidijus Dragūnas',
      'Selas',
      'Rytis Cicinas',
      'Radžis',
      'Žilvinas Žvagulis',
      'Irena Starošaitė',
      'Vudis',
      'Mino',
      'Radistai',
      'Jonas Nainys',
      'Rolandas Mackevičius',
      'Whydotas',
      'Flying Saucer Gang',
      'BA.',
      'G&G Sindikatas',
      'Jovani',
      'Dynoro',
    ],
  },
}
