export const wordHints: Record<string, string> = {
  'Cepelinas': 'Tai yra tradicinis valgomas dalykas',
  'Gitanas Nausėda': 'Tai yra aukštas valstybės pareigūnas',
  'Maybachas': 'Tai yra labai prabangi transporto priemonė',
  'Auksinis kardas': 'Tai yra ginklas, pagamintas iš brangaus metalo',
  'Krabas': 'Tai yra jūros gyvūnas',
  'Šaltibarščiai': 'Tai yra vasariškas lietuviškas patiekalas',
  'Pink Soup': 'Tai yra patiekalas, žinomas ir angliškai',
  'Luktelk': 'Tai yra populiarus lietuviškas projektas',
  'The Roop': 'Tai yra lietuviška muzikos grupė',
  'Marozas': 'Tai yra žinomas lietuviškas personažas',
  'Forsas': 'Tai yra lietuviškas serialas',
  'Perekūpas': 'Tai yra žinomas lietuviškas personažas',
  'Žalgiris': 'Tai yra garsi lietuviška sporto komanda',
  'Krepšinis': 'Tai yra labai populiarus Lietuvoje sportas',
  'Kugelis': 'Tai yra tradicinis bulvinis patiekalas',
  'Vėdarai': 'Tai yra tradicinis lietuviškas valgis',
  'Gariūnai': 'Tai yra vieta Vilniuje, susijusi su prekyba',
  'Akropolis': 'Tai yra didelis prekybos centras',
  'Boltukas': 'Tai yra populiarus senas automobilis',
  'Woltas': 'Tai yra maisto pristatymo aplikacija',
  'Maxima': 'Tai yra lietuviškas prekybos tinklas',
  'Lidlas': 'Tai yra vokiška parduotuvė Lietuvoje',
  'Eurovizija': 'Tai yra tarptautinis muzikos konkursas',
  'Vilnius': 'Tai yra sostinė',
  'Kaunas': 'Tai yra Lietuvos miestas',
  'Palanga': 'Tai yra pajūrio kurortas',
  'Šventoji': 'Tai yra vieta prie Baltijos jūros',
  'Nida': 'Tai yra vieta Kuršių nerijoje',
  'Trakai': 'Tai yra vieta su istorine pilis',
  'Kryžių kalnas': 'Tai yra religinė ir istorinė vieta',
  'Gedimino pilis': 'Tai yra svarbus istorinis pastatas',
  'Užupis': 'Tai yra meninis Vilniaus rajonas',
  'Konstitucija': 'Tai yra pagrindinis šalies įstatymas',
  'Mercedes 124': 'Tai yra klasikinis vokiškas automobilis',
  'Kregždė': 'Tai yra skraidantis gyvūnas',
  'Ryklis': 'Tai yra pavojingas plėšrūnas vandenyne',
  'Bulka': 'Tai yra minkštas kepinys',
  'Silkė': 'Tai yra žuvis',
  'Passatas': 'Tai yra Volkswagen automobilio modelis',
  'Varškės sūrelis': 'Tai yra pieno produktas',
  'Magija': 'Tai yra mistinis konceptas',
  'Džiugas': 'Tai yra lietuviškas sūris',
  'Šakotis': 'Tai yra tradicinis lietuviškas tortas',
  'Grybukai': 'Tai yra valgomas užkandis',
  'Kebabas': 'Tai yra populiarus gatvės maistas',
  'Bambalis': 'Tai yra žargoninis žodis',
  'Alutis': 'Tai yra alkoholinis gėrimas',
  'Samagonas': 'Tai yra naminis stiprus gėrimas',
  'Konservai': 'Tai yra maistas skardinėse',
  'Valstiečiai': 'Tai yra lietuviška politinė partija',
  'Laisvės partija': 'Tai yra lietuviška politinė partija',
  'Andrius Tapinas': 'Tai yra žinomas lietuvių žurnalistas',
  'Skirmantas Malinauskas': 'Tai yra žinomas Lietuvos politikas',
  'Minedas': 'Tai yra žinomas interneto kūrėjas',
  'Antanas Juknevičius': 'Tai yra žinomas lietuvis',
  'Dakaras': 'Tai yra garsiausias pasaulio automobilių ralis',
  'Žydrūnas Savickas': 'Tai yra stipriausias pasaulio sportininkas',
  'Arvydas Sabonis': 'Tai yra krepšinio legenda',
  'Jonas Valančiūnas': 'Tai yra dabartinis NBA krepšininkas',
  'Pijokas': 'Tai yra žmogus, mėgstantis gerti',
  'Švyturys': 'Tai yra žinomas lietuviškas alus',
  'Kalnapilis': 'Tai yra žinomas lietuviškas alus',
  'OG Version': 'Tai yra originalus dalykas',
  'Lietuva': 'Tai yra Baltijos valstybė',
  'Gintaras': 'Tai yra Baltijos jūros lobis',
  'Linas': 'Tai yra augalas, susijęs su Lietuva',
  'Duona': 'Tai yra pagrindinis maisto produktas',
  'Pienas': 'Tai yra baltas gėrimas iš gyvūnų',
  'Medus': 'Tai yra saldus bičių produktas',
  'Vytis': 'Tai yra Lietuvos simbolis',
  'Gediminas': 'Tai yra istorinė Lietuvos asmenybė',
  'Vytautas': 'Tai yra istorinė Lietuvos asmenybė',
  'Mindaugas': 'Tai yra pirmasis Lietuvos karalius',
  'Dalia Grybauskaitė': 'Tai yra buvusi Lietuvos prezidentė',
  'Valdas Adamkus': 'Tai yra buvęs Lietuvos prezidentas',
  'Rūta Meilutytė': 'Tai yra žinoma sportininkė',
  'Donatas Montvydas': 'Tai yra žinomas lietuvis atlikėjas',
  'Marijonas Mikutavičius': 'Tai yra žinomas lietuvis dainininkas',
  'Andrius Mamontovas': 'Tai yra lietuvių roko legenda',
  'Jazzu': 'Tai yra žinoma lietuvė atlikėja',
  'Beata Nicholson': 'Tai yra žinoma lietuvė atlikėja',
  'Martynas Levickis': 'Tai yra žinomas muzikantas',
  'Monika Liu': 'Tai yra Lietuvos Eurovizijos atstovė',
  'Gabrielius Landsbergis': 'Tai yra žinomas Lietuvos politikas',
  'Ingrida Šimonytė': 'Tai yra aukšta Lietuvos pareigūnė',
  'Ramūnas Karbauskis': 'Tai yra žinomas Lietuvos politikas',
  'Viktoras Uspaskich': 'Tai yra kontroversiškas Lietuvos politikas',
  'Rolandas Paksas': 'Tai yra buvęs Lietuvos prezidentas',
  'Vytautas Šapranauskas': 'Tai yra žinomas lietuvis humoristas',
  'Algis Greitai': 'Tai yra žinomas lietuvis',
  'Mantas Katleris': 'Tai yra žinomas interneto veikėjas',
  'Justinas Jankevičius': 'Tai yra žinomas lietuvis dainininkas',
  'Indrė Stonkuvienė': 'Tai yra žinoma lietuvė',
  'Naglis Bierancas': 'Tai yra žinomas lietuvis',
  'Sūrūs agurkėliai': 'Tai yra rūgštus valgomas dalykas',
  'Silkė pataluose': 'Tai yra tradicinis lietuviškas patiekalas',
  'Grybai': 'Tai yra miško produktas',
  'Miškas': 'Tai yra gamtos vieta su medžiais',
  'Kiesa': 'Tai yra žargoninis žodis',
  'Giedrė Beleauskaitė': 'Tai yra žinoma lietuvė',
  'Karolina Meschino': 'Tai yra žinoma lietuvė',
  'Agnė Jagelavičiūtė': 'Tai yra žinoma viešoji asmenybė',
  'Orijus Gasanovas': 'Tai yra žinomas lietuvis',
  'Paulius de Miko': 'Tai yra žinomas lietuvis',
  'Daina Bosas': 'Tai yra žinomas lietuvis',
  'Natalija Bunkė': 'Tai yra žinoma lietuvė atlikėja',
  'Mia': 'Tai yra žinoma lietuvė',
  'Vidas Bareikis': 'Tai yra žinomas lietuvis aktorius',
  'Egidijus Dragūnas': 'Tai yra žinomas lietuvis muzikantas',
  'Selas': 'Tai yra žinomas lietuvis',
  'Rytis Cicinas': 'Tai yra žinomas lietuvis',
  'Radžis': 'Tai yra žinomas lietuvis',
  'Žilvinas Žvagulis': 'Tai yra žinomas lietuvis',
  'Irena Starošaitė': 'Tai yra žinoma lietuvė',
  'Vudis': 'Tai yra žinomas lietuvis',
  'Mino': 'Tai yra žinomas lietuvis',
  'Radistai': 'Tai yra lietuviška muzikos grupė',
  'Jonas Nainys': 'Tai yra žinomas lietuvis',
  'Rolandas Mackevičius': 'Tai yra žinomas lietuvis',
  'Whydotas': 'Tai yra žinomas interneto kūrėjas',
  'Flying Saucer Gang': 'Tai yra lietuviška muzikos grupė',
  'BA.': 'Tai yra žinomas lietuvis rapuotojas',
  'G&G Sindikatas': 'Tai yra lietuviška muzikos grupė',
  'Jovani': 'Tai yra labai populiari daina',
  'Dynoro': 'Tai yra žinomas lietuvis muzikantas',
  'Jautiena': 'Tai yra mėsos rūšis',
  'Kiauliena': 'Tai yra mėsos rūšis',
  'Vištiena': 'Tai yra paukštienos rūšis',
  'Kumpis': 'Tai yra rūkyta mėsa',
  'Dešrelės': 'Tai yra mėsos gaminys',
  'Kotletas': 'Tai yra maltos mėsos patiekalas',
  'Blynai': 'Tai yra plokšti kepiniai',
  'Šaukštas': 'Tai yra stalo įrankis',
  'Šakutė': 'Tai yra stalo įrankis su šakutėmis',
  'Peilis': 'Tai yra pjovimo įrankis',
  'Kibiras': 'Tai yra talpykla skysčiams',
  'Šluota': 'Tai yra valymo įrankis',
  'Šampūnas': 'Tai yra plaukų priežiūros priemonė',
  'Rankšluostis': 'Tai yra tekstilės gaminys voniai',
  'BMW': 'Tai yra vokiškas automobilis',
  'Audi': 'Tai yra vokiškas automobilis',
  'Volkswagen': 'Tai yra vokiškas automobilis',
  'Toyota': 'Tai yra japoniškas automobilis',
  'Renault': 'Tai yra prancūziškas automobilis',
  'Dviratis': 'Tai yra transporto priemonė su dviem ratais',
  'Paspirtukas': 'Tai yra mažas asmeninis transportas',
  'Kojinės': 'Tai yra drabužio dalis kojoms',
  'Kelnes': 'Tai yra drabužio dalis',
  'Striukė': 'Tai yra viršutinis drabužis',
  'Batus': 'Tai yra avalynė',
  'Kepurė': 'Tai yra galvos apdangalas',
  'Piniginė': 'Tai yra aksesuaras pinigams laikyti',
  'Diržas': 'Tai yra aksesuaras kelnėms',
  'Telefonas': 'Tai yra ryšio elektroninis įrenginys',
  'Kompiuteris': 'Tai yra elektroninis įrenginys darbui',
  'Ausinės': 'Tai yra elektroninis priedas muzikai klausyti',
  'Kroviklis': 'Tai yra elektroninis priedas baterijai krauti',
  'Atsuktuvas': 'Tai yra rankinis įrankis',
  'Šaldytuvas': 'Tai yra buitinis prietaisas maistui laikyti',
  'Virdulys': 'Tai yra buitinis prietaisas vandeniui karšti',
}

export type WordCategoryKey = 'lithuanian'

export type WordCategory = {
  label: string
  words: string[]
}

export const wordCategories: Record<WordCategoryKey, WordCategory> = {
  lithuanian: {
    label: 'Lietuviška DB',
    words: [
      'Cepelinas',
      'Gitanas Nausėda',
      'Maybachas',
      'Auksinis kardas',
      'Krabas',
      'Šaltibarščiai',
      'Pink Soup',
      'Luktelk',
      'The Roop',
      'Marozas',
      'Forsas',
      'Perekūpas',
      'Žalgiris',
      'Krepšinis',
      'Kugelis',
      'Vėdarai',
      'Gariūnai',
      'Akropolis',
      'Boltukas',
      'Woltas',
      'Maxima',
      'Lidlas',
      'Eurovizija',
      'Vilnius',
      'Kaunas',
      'Palanga',
      'Šventoji',
      'Nida',
      'Trakai',
      'Kryžių kalnas',
      'Gedimino pilis',
      'Užupis',
      'Konstitucija',
      'Mercedes 124',
      'Kregždė',
      'Ryklis',
      'Bulka',
      'Silkė',
      'Passatas',
      'Varškės sūrelis',
      'Magija',
      'Džiugas',
      'Šakotis',
      'Grybukai',
      'Kebabas',
      'Bambalis',
      'Alutis',
      'Samagonas',
      'Konservai',
      'Valstiečiai',
      'Laisvės partija',
      'Andrius Tapinas',
      'Skirmantas Malinauskas',
      'Minedas',
      'Antanas Juknevičius',
      'Dakaras',
      'Žydrūnas Savickas',
      'Arvydas Sabonis',
      'Jonas Valančiūnas',
      'Pijokas',
      'Švyturys',
      'Kalnapilis',
      'OG Version',
      'Lietuva',
      'Gintaras',
      'Linas',
      'Duona',
      'Pienas',
      'Medus',
      'Vytis',
      'Gediminas',
      'Vytautas',
      'Mindaugas',
      'Dalia Grybauskaitė',
      'Valdas Adamkus',
      'Rūta Meilutytė',
      'Donatas Montvydas',
      'Marijonas Mikutavičius',
      'Andrius Mamontovas',
      'Jazzu',
      'Beata Nicholson',
      'Martynas Levickis',
      'Monika Liu',
      'Gabrielius Landsbergis',
      'Ingrida Šimonytė',
      'Ramūnas Karbauskis',
      'Viktoras Uspaskich',
      'Rolandas Paksas',
      'Vytautas Šapranauskas',
      'Algis Greitai',
      'Mantas Katleris',
      'Justinas Jankevičius',
      'Indrė Stonkuvienė',
      'Naglis Bierancas',
      'Sūrūs agurkėliai',
      'Silkė pataluose',
      'Grybai',
      'Miškas',
      'Kiesa',
      'Giedrė Beleauskaitė',
      'Karolina Meschino',
      'Agnė Jagelavičiūtė',
      'Orijus Gasanovas',
      'Paulius de Miko',
      'Daina Bosas',
      'Natalija Bunkė',
      'Mia',
      'Vidas Bareikis',
      'Egidijus Dragūnas',
      'Selas',
      'Rytis Cicinas',
      'Radžis',
      'Žilvinas Žvagulis',
      'Irena Starošaitė',
      'Vudis',
      'Mino',
      'Radistai',
      'Jonas Nainys',
      'Rolandas Mackevičius',
      'Whydotas',
      'Flying Saucer Gang',
      'BA.',
      'G&G Sindikatas',
      'Jovani',
      'Dynoro',
      'Jautiena',
      'Kiauliena',
      'Vištiena',
      'Kumpis',
      'Dešrelės',
      'Kotletas',
      'Blynai',
      'Šaukštas',
      'Šakutė',
      'Peilis',
      'Kibiras',
      'Šluota',
      'Šampūnas',
      'Rankšluostis',
      'BMW',
      'Audi',
      'Volkswagen',
      'Toyota',
      'Renault',
      'Dviratis',
      'Paspirtukas',
      'Kojinės',
      'Kelnes',
      'Striukė',
      'Batus',
      'Kepurė',
      'Piniginė',
      'Diržas',
      'Telefonas',
      'Kompiuteris',
      'Ausinės',
      'Kroviklis',
      'Atsuktuvas',
      'Šaldytuvas',
      'Virdulys',
    ],
  },
}
